// org.carewebframework.web.angular-parent/org.carewebframework.web.angular.example/src/main/webjar/pomodoro.ts
import { Component } from '@angular/core';

// Pomodoro timer component
// Note: bootstrapping is handled automatically.
// Note: that we do not specify a selector as it will be assigned during bootstrapping.
@Component({
  template: `
    <div class="text-center">
      <img src="webjars/cwf-angular-example/assets/img/pomodoro.png" alt="Pomodoro">
      <h1> {{ minutes }}:{{ seconds | number: '2.0' }} </h1>
      <p>
        <button (click)="togglePause()"
          class="btn btn-danger">
          {{ buttonLabel }}
        </button>
      </p>
    </div>
`
})
class PomodoroComponent {
  minutes: number;
  seconds: number;
  isPaused: boolean;
  buttonLabel: string;

  constructor() {
    this.resetPomodoro();
    setInterval(() => this.tick(), 1000);
  }

  resetPomodoro(): void {
    this.isPaused = true;
    this.minutes = 24;
    this.seconds = 59;
    this.buttonLabel = 'Start';
  }

  private tick(): void {
    if (!this.isPaused) {
      this.buttonLabel = 'Pause';

      if (--this.seconds < 0) {
        this.seconds = 59;
        if (--this.minutes < 0) {
          this.resetPomodoro();
        }
      }
    }
  }

  togglePause(): void {
    this.isPaused = !this.isPaused;
    if (this.minutes < 24 || this.seconds < 59) {
      this.buttonLabel = this.isPaused ? 'Resume' : 'Pause';
    }
  }
}

// Must export component to be bootstrapped as AngularComponent

let AngularComponent = PomodoroComponent;
export { AngularComponent };
  
/* Any additional metadata to be passed to the application module during bootstrapping
 * may be exported as in the following example:
 * 
 *      let ngModule : NgModule = { providers: [ AService ] };
 *      export { ngModule };
 * 
 * This will be merged with the default metadata prior to bootstrapping.
*/

// org.carewebframework.web.react-parent/org.carewebframework.web.react.example/src/main/webjar/pomodoro.js
'use strict';

define('cwf-react-pomodoro', [ 'react', 'react-dom' ],
	function(React, ReactDOM) {

		var ImageClass = React.createClass({
			render : function() {
				return React.createElement('img', {
					src : 'webjars/cwf-react-example/assets/img/pomodoro.png',
					alt : 'Pomodoro'
				});
			}
		});

		var CounterClass = React.createClass({
			formatTime : function() {
				return this.props.minutes + ':' + this.props.seconds;
			},

			render : function() {
				return React.createElement('h1', {}, this.formatTime());
			}
		});

		var ButtonClass = React.createClass({
			render : function() {
				return React.createElement('button', {
					className : 'btn btn-danger',
					onClick : this.props.onClick
				}, this.props.buttonLabel);
			}
		});

		// Return the class for the top level component.
		
		return React.createClass({
			getInitialState : function() {
				return {
					isPaused : true,
					minutes : 24,
					seconds : 59,
					buttonLabel : 'Start'
				}
			},

			componentDidMount : function() {
				var self = this;

				this.timer = setInterval(function() {
					self.tick();
				}, 1000);
			},

			componentWillUnmount : function() {
				clearInterval(this.timer);
				delete this.timer;
			},

			resetPomodoro : function() {
				this.setState(this.getInitialState());
			},

			tick : function() {
				if (!this.state.isPaused) {
					var newState = {};

					newState.buttonLabel = 'Pause';
					newState.seconds = this.state.seconds - 1;

					if (newState.seconds < 0) {
						newState.seconds = 59;
						newState.minutes = this.state.minutes - 1;

						if (newState.minutes < 0) {
							return this.resetPomodoro();
						}
					}

					this.setState(newState);
				}
			},

			togglePause : function() {
				var newState = {};

				newState.isPaused = !this.state.isPaused;

				if (this.state.minutes < 24 || this.state.seconds < 59) {
					newState.buttonLabel = newState.isPaused ? 'Resume' : 'Pause';
				}

				this.setState(newState);
			},

			render : function() {
				return React.createElement('div', {
					className : 'text-center'
				}, [
					React.createElement(ImageClass, {
						key: 'image'
					}),
					React.createElement(CounterClass, {
						key : 'counter',
						minutes : this.state.minutes,
						seconds : this.state.seconds
					}),
					React.createElement(ButtonClass, {
						key : 'button',
						buttonLabel : this.state.buttonLabel,
						onClick : this.togglePause
					})
				]);
			}
		});
	});
